name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test_spm_mac:
    runs-on: macos-14
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.2"
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test

  build_and_test_spm_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: sersoft-gmbh/swifty-linux-action@v3
        with:
          release-version: "5.9.2"
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test --enable-test-discovery

  build_and_test_ios:
    runs-on: macos-14
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.2"
      - uses: actions/checkout@v2
      - run: xcodebuild -scheme Hightouch test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13'

  build_and_test_tvos:
    runs-on: macos-14
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.2"
      - uses: actions/checkout@v2
      - run: xcodebuild -scheme Hightouch test -sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV'

  build_and_test_watchos:
    runs-on: macos-14
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.2"
      - uses: actions/checkout@v2
      - run: xcodebuild -scheme Hightouch test -sdk watchsimulator -destination 'platform=watchOS Simulator,name=Apple Watch Series 8 (45mm)'

  # build_and_test_visionos:
  #   runs-on: macos-14
  #   steps:
  #     - uses: maxim-lobanov/setup-xcode@v1
  #       with:
  #         xcode-version: "15.2"
  #     - uses: actions/checkout@v2
  #     - run: defaults write com.apple.dt.Xcode AllowUnsupportedVisionOSHost -bool YES
  #     - run: defaults write com.apple.CoreSimulator AllowUnsupportedVisionOSHost -bool YES
  #     - run: xcodebuild -downloadPlatform visionOS
  #     - run: echo - skip until apple fixes this - xcodebuild -scheme Hightouch test -sdk xrsimulator -destination 'platform=visionOS Simulator,name=Apple Vision Pro'
  #     - run: xcodebuild -scheme Segment -sdk xrsimulator -destination 'platform=visionOS Simulator,name=Apple Vision Pro'

  build_and_test_examples:
    runs-on: macos-14
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.2"
      - uses: actions/checkout@v2
      - name: build for ios simulator
        run: |
          cd Examples/apps/BasicExample
          xcodebuild -workspace "BasicExample.xcworkspace" -scheme "BasicExample" -sdk iphonesimulator
      - name: build for ios simulator
        run: |
          cd Examples/apps/ObjCExample
          xcodebuild -workspace "ObjCExample.xcworkspace" -scheme "ObjCExample" -sdk iphonesimulator
      - name: build for ios simulator
        run: |
          cd Examples/apps/SegmentUIKitExample
          xcodebuild -workspace "SegmentUIKitExample.xcworkspace" -scheme "SegmentUIKitExample" -sdk iphonesimulator
      - name: build for ios simulator
        run: |
          cd Examples/apps/SegmentWeatherWidget
          xcodebuild -workspace "SegmentWeatherWidget.xcworkspace" -scheme "SegmentWeatherWidget" -sdk iphonesimulator
      - name: build for mac catalyst
        run: |
          cd Examples/apps/SegmentUIKitExample
          xcodebuild -workspace "SegmentUIKitExample.xcworkspace" -scheme "SegmentUIKitExample" -destination 'platform=macOS,variant=Mac Catalyst'
